In [2]:
import requests as rq
import pandas as pd
import datetime as dt
from time import sleep

In [3]:
with open('accessToken.txt',"r") as file:
    access_token = file.read()
url = "https://api.upstox.com/v2/user/profile"
headers = {
    'accept': 'application/json',
    'Api-Version': '2.0',
    'Authorization': f'Bearer {access_token}'}
response = rq.get(url, headers=headers)
print(response.json()['status'])

success

In [4]:
df = pd.read_csv("https://assets.upstox.com/market-quote/instruments/exchange/complete.csv.gz")

In [6]:
def filter_df(df,lot_size):
    df = df[(df['exchange'] == 'NSE_FO') &(df['instrument_type'] == 'OPTIDX') &(df['lot_size'] == lot_size)]
    df = df[df['expiry'] ==  min(df['expiry'].unique())]
    return df

In [7]:
BNDF = filter_df(df,15)

In [10]:
BNDF[(BNDF['strike'] == 47800) & (BNDF['option_type'] == 'CE')]['instrument_key'].iloc[0]

'NSE_FO|64008'

In [25]:

url = "https://api.upstox.com/v2/market-quote/quotes"
# instrument = 'NSE_FO|64008'
headers = {
    'accept': 'application/json',
    'Api-Version': '2.0',
    'Authorization': f'Bearer {access_token}'}
payload= {'symbol': ~'}
response = rq.get(url,headers=headers, params=payload)
print(response.json())

{'status': 'success', 'data': {'NSE_FO:BANKNIFTY23DEC47800CE': {'ohlc': {'open': 200.0, 'high': 629.95, 'low': 112.35, 'close': 545.0}, 'depth': {'buy': [{'quantity': 30, 'price': 531.4, 'orders': 1}, {'quantity': 30, 'price': 531.35, 'orders': 1}, {'quantity': 30, 'price': 525.65, 'orders': 1}, {'quantity': 120, 'price': 525.6, 'orders': 1}, {'quantity': 30, 'price': 524.35, 'orders': 1}], 'sell': [{'quantity': 8040, 'price': 545.0, 'orders': 20}, {'quantity': 15, 'price': 545.5, 'orders': 1}, {'quantity': 30, 'price': 545.75, 'orders': 1}, {'quantity': 45, 'price': 545.8, 'orders': 2}, {'quantity': 90, 'price': 545.85, 'orders': 1}]}, 'timestamp': '2023-12-21T17:11:56.354+05:30', 'instrument_token': 'NSE_FO|64008', 'symbol': 'BANKNIFTY23DEC47800CE', 'last_price': 545.0, 'volume': 35066490, 'average_price': 317.56, 'oi': 849105.0, 'net_change': 297.65, 'total_buy_quantity': 41355.0, 'total_sell_quantity': 42015.0, 'lower_circuit_limit': 0.05, 'upper_circuit_limit': 1304.7, 'last_trade_time': '1703152799934', 'oi_day_high': 1102215.0, 'oi_day_low': 580140.0}}}

In [29]:
url = "https://api.upstox.com/v2/market-quote/ltp"
# instrument = 'NSE_FO|64008'
headers = {
    'accept': 'application/json',
    'Api-Version': '2.0',
    'Authorization': f'Bearer {access_token}'}
payload= {'symbol': 'NSE_FO|64008'}#interval
response = rq.get(url,headers=headers, params=payload)
print(response.json())

{'status': 'success', 'data': {'NSE_FO:BANKNIFTY23DEC47800CE': {'last_price': 545.0, 'instrument_token': 'NSE_FO|64008'}}}

In [34]:
# last_price
response.json()['data']['NSE_FO:BANKNIFTY23DEC47800CE']['last_price']

545.0

In [35]:
from_date =(dt.datetime.now() - dt.timedelta(days=4)).date()
to_date =dt.datetime.now().date()
to_date

datetime.date(2023, 12, 21)

In [37]:
url = f"https://api.upstox.com/v2/historical-candle/NSE_FO|64008/1minute/{to_date}/{from_date}"
# url = "https://api.upstox.com/v2/historical-candle/:instrument_key/:~/:to_date/:from_date"

payload={}
headers = {
    'accept': 'application/json',
    'Api-Version': '2.0',
    'Authorization': f'Bearer {access_token}'}
response = rq.get(url, headers=headers).json()

In [42]:
Data = pd.DataFrame(response['data']['candles'])
Data.columns = ['date','open','high','low','close','volume','oi']
Data

,date,open,high,low,close,volume,oi
0,2023-12-20T15:29:00+05:30,193.05,200.00,170.00,190.40,51705,580830
1,2023-12-20T15:28:00+05:30,193.15,200.00,189.00,193.05,72000,580830
2,2023-12-20T15:27:00+05:30,200.50,201.80,192.20,193.05,47205,580830
3,2023-12-20T15:26:00+05:30,206.25,206.30,200.00,200.05,52995,576030
4,2023-12-20T15:25:00+05:30,222.75,222.90,203.10,206.05,63810,576030
...,...,...,...,...,...,...,...
1120,2023-12-18T09:19:00+05:30,561.10,562.65,549.45,554.20,27135,151740
1121,2023-12-18T09:18:00+05:30,556.10,566.70,555.90,561.55,28410,151740
1122,2023-12-18T09:17:00+05:30,549.45,557.20,544.00,557.20,13965,151740
1123,2023-12-18T09:16:00+05:30,559.80,582.10,543.75,545.55,12195,132210
1124,2023-12-18T09:15:00+05:30,600.05,627.75,559.90,560.75,12690,132210

In [45]:
# intraday candle =
url = "https://api.upstox.com/v2/historical-candle/intraday/NSE_FO|64008/1minute"

headers = {
    'accept': 'application/json',
    'Api-Version': '2.0',
    'Authorization': f'Bearer {access_token}'}
res = rq.get(url, headers=headers).json()

In [49]:
Data1 = pd.DataFrame(res['data']['candles'])
Data1.columns = ['date','open','high','low','close','volume','oi']
Data1

                          date    open    high     low   close  volume      oi
0    2023-12-21T15:29:00+05:30  544.45  546.20  511.00  545.00  122970  849105
1    2023-12-21T15:28:00+05:30  529.50  548.90  525.00  544.40   78765  849105
2    2023-12-21T15:27:00+05:30  524.15  533.90  519.30  527.50   65355  849105
3    2023-12-21T15:26:00+05:30  513.90  526.10  512.00  524.10   63090  830190
4    2023-12-21T15:25:00+05:30  509.00  518.00  496.40  513.90  126315  830190
..                         ...     ...     ...     ...     ...     ...     ...
370  2023-12-21T09:19:00+05:30  194.30  194.50  155.55  157.25  152865  738405
371  2023-12-21T09:18:00+05:30  163.05  199.55  160.10  194.90  173640  738405
372  2023-12-21T09:17:00+05:30  155.80  183.20  152.00  162.65  161880  738405
373  2023-12-21T09:16:00+05:30  143.60  162.50  141.00  155.95  228450  580140
374  2023-12-21T09:15:00+05:30  200.00  200.00  112.35  143.80  587505  580140

[375 rows x 7 columns]

In [53]:
Data1['date'] = pd.to_datetime(Data1['date']).apply(lambda x:str(x).split("+")[0])
Data1

                    date    open    high     low   close  volume      oi
0    2023-12-21 15:29:00  544.45  546.20  511.00  545.00  122970  849105
1    2023-12-21 15:28:00  529.50  548.90  525.00  544.40   78765  849105
2    2023-12-21 15:27:00  524.15  533.90  519.30  527.50   65355  849105
3    2023-12-21 15:26:00  513.90  526.10  512.00  524.10   63090  830190
4    2023-12-21 15:25:00  509.00  518.00  496.40  513.90  126315  830190
..                   ...     ...     ...     ...     ...     ...     ...
370  2023-12-21 09:19:00  194.30  194.50  155.55  157.25  152865  738405
371  2023-12-21 09:18:00  163.05  199.55  160.10  194.90  173640  738405
372  2023-12-21 09:17:00  155.80  183.20  152.00  162.65  161880  738405
373  2023-12-21 09:16:00  143.60  162.50  141.00  155.95  228450  580140
374  2023-12-21 09:15:00  200.00  200.00  112.35  143.80  587505  580140

[375 rows x 7 columns]